name: Publish
on:
  push:
    branches:
      - "*"
      - "!master"
      - "!main"
env:
  DEPLOY_DESTINATION: ${{ secrets.DEPLOY_DESTINATION }}
  DEPLOY_PORT: ${{ secrets.DEPLOY_PORT }}
  SSHKEY: ${{ secrets.SSHKEY }}
  SSHPUB: ${{ secrets.SSHPUB }}

jobs:
  build:
    name: Build
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        node-version: [23.x]
    permissions:
      contents: read
      security-events: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependendencies
        run: npm install

      - name: Test
        run: npm run test

      - name: Build
        run: npm run build

      - name: Deploy
        run: |
          eval "$(ssh-agent -s)" > /dev/null
          ssh-add ${{ secrets.SSHKEY }}
          scp -P ${{ secrets.DEPLOY_PORT }} -o StrictHostKeyChecking=no dist/* ${{ secrets.DEPLOY_DESTINATION }}
